//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iosWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class blogDataEntities : DbContext
    {
        public blogDataEntities()
            : base("name=blogDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articles> Articles { get; set; }
        public DbSet<Collection> Collection { get; set; }
        public DbSet<Comments> Comments { get; set; }
        public DbSet<HeadImg> HeadImg { get; set; }
        public DbSet<Info> Info { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual int addHeadimg(string imgPath, ObjectParameter imgID)
        {
            var imgPathParameter = imgPath != null ?
                new ObjectParameter("imgPath", imgPath) :
                new ObjectParameter("imgPath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addHeadimg", imgPathParameter, imgID);
        }
    
        public virtual int addInfo(Nullable<bool> sex, Nullable<System.DateTime> birthday, string email, string qq, Nullable<System.DateTime> signtime, ObjectParameter infoID)
        {
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(bool));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var qqParameter = qq != null ?
                new ObjectParameter("qq", qq) :
                new ObjectParameter("qq", typeof(string));
    
            var signtimeParameter = signtime.HasValue ?
                new ObjectParameter("signtime", signtime) :
                new ObjectParameter("signtime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addInfo", sexParameter, birthdayParameter, emailParameter, qqParameter, signtimeParameter, infoID);
        }
    }
}
