//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iosWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Articles = new HashSet<Articles>();
            this.Collection = new HashSet<Collection>();
            this.Comments = new HashSet<Comments>();
            this.Messages = new HashSet<Messages>();
            this.Messages1 = new HashSet<Messages>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int headimgID { get; set; }
        public System.DateTime rgtime { get; set; }
        public int infoID { get; set; }
        public int bloghot { get; set; }
    
        public virtual ICollection<Articles> Articles { get; set; }
        public virtual ICollection<Collection> Collection { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual HeadImg HeadImg { get; set; }
        public virtual Info Info { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Messages> Messages1 { get; set; }
    }
}
